import { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Search, Plus, FileText, Download, ChevronRight, Clock, Edit3, CheckCircle2, History } from "lucide-react";
import { REPORTS } from "../mocks/reports";
import GlassCard, { glassPanelStyle } from "../components/GlassCard";
import { ReportStatusBadge } from "../components/StatusBadge";
import LiquidOrb from "../components/LiquidOrb";
import type { Report } from "../mocks/types";

const DRAFT_TEXT = `CHARGESHEET / INCIDENT SUMMARY DRAFT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by Prahari AI on ${new Date().toLocaleDateString("en-IN")}
Karnataka State Police — Classified Document

SECTION 1: INCIDENT OVERVIEW
An incident was reported on the specified date and time within the jurisdiction of the named Police Station. Initial assessment indicates that the matter falls under the purview of the Indian Penal Code / BNSS provisions applicable to the cited offence category.

SECTION 2: FACTS OF THE CASE
Based on the information provided, the following material facts are established:
  (a) The complainant has disclosed the circumstances leading to the incident;
  (b) Preliminary evidence has been documented per KSP standard operating procedures;
  (c) Relevant forensic procedures have been or are being initiated.

SECTION 3: LEGAL PROVISIONS
The offence(s) attract the following provisions:
  — Section [auto-populated from case type]
  — BNSS 2023 equivalent provisions
  — Applicable local laws

SECTION 4: RECOMMENDED ACTION
Investigation to proceed under the supervision of the designated Investigating Officer. Final chargesheet to be filed within 60 days per statutory requirement.

[AI Suggestion] Add witness statement references — Section 2(b)
[AI Suggestion] Include FIR number if already registered

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This is an AI-generated draft. All facts must be verified by the Investigating Officer before submission.`;

type GenerateState = "idle" | "thinking" | "streaming" | "done";

function StreamingText({ text, onDone }: { text: string; onDone: () => void }) {
  const [visible, setVisible] = useState("");
  useEffect(() => {
    let i = 0;
    const t = setInterval(() => {
      i += 4;
      setVisible(text.slice(0, i));
      if (i >= text.length) { clearInterval(t); onDone(); }
    }, 16);
    return () => clearInterval(t);
  }, [text]);
  return (
    <pre className="text-xs leading-relaxed whitespace-pre-wrap font-mono" style={{ color: "rgba(255,255,255,0.75)" }}>
      {visible}
      <span className="animate-pulse" style={{ color: "#C9A227" }}>▊</span>
    </pre>
  );
}

function ReportRow({ report, selected, onClick }: { report: Report; selected: boolean; onClick: () => void }) {
  return (
    <motion.button
      onClick={onClick}
      whileHover={{ x: 2 }}
      className="w-full flex items-center gap-3 px-4 py-3.5 text-left transition-all"
      style={{
        background: selected ? "rgba(201,162,39,0.08)" : "transparent",
        borderLeft: selected ? "2px solid #C9A227" : "2px solid transparent",
        borderBottom: "1px solid rgba(255,255,255,0.06)",
      }}
    >
      <div className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0"
        style={{ background: "rgba(63,92,134,0.25)", color: "#7BA7CC" }}>
        <FileText className="w-4 h-4" />
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-sm font-semibold truncate" style={{ color: "rgba(255,255,255,0.85)" }}>{report.title}</p>
        <div className="flex items-center gap-2 mt-0.5">
          <span className="text-[10px]" style={{ color: "rgba(255,255,255,0.3)" }}>{report.caseId}</span>
          <span className="text-[10px]" style={{ color: "rgba(255,255,255,0.2)" }}>·</span>
          <ReportStatusBadge status={report.status} />
        </div>
      </div>
      <ChevronRight className="w-4 h-4 shrink-0" style={{ color: "rgba(255,255,255,0.2)" }} />
    </motion.button>
  );
}

export default function Reports() {
  const [reports, setReports] = useState<Report[]>(REPORTS);
  const [selected, setSelected] = useState<Report | null>(REPORTS[0]);
  const [search, setSearch] = useState("");
  const [showBuilder, setShowBuilder] = useState(false);
  const [genState, setGenState] = useState<GenerateState>("idle");
  const [genCaseId, setGenCaseId] = useState("");
  const [genType, setGenType] = useState("Incident Summary");
  const [genNotes, setGenNotes] = useState("");
  const [showHistory, setShowHistory] = useState(false);

  const filtered = reports.filter(r =>
    r.title.toLowerCase().includes(search.toLowerCase()) ||
    r.caseId.toLowerCase().includes(search.toLowerCase())
  );

  const handleGenerate = () => {
    setGenState("thinking");
    setTimeout(() => setGenState("streaming"), 2500);
  };

  const handleDownload = () => {
    const blob = new Blob([selected?.sections.map(s => `## ${s.heading}\n${s.content}`).join("\n\n") ?? ""], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${selected?.id ?? "report"}.txt`; a.click();
    URL.revokeObjectURL(url);
  };

  const hasActiveSelection = !!selected || showBuilder;

  return (
    <div className="flex h-full overflow-hidden">

      {/* ── Left: Report List ─────────────────────────────────── */}
      <div 
        className={`flex-col w-full md:w-80 shrink-0 border-r ${hasActiveSelection ? "hidden md:flex" : "flex"}`} 
        style={{ borderColor: "rgba(255,255,255,0.07)" }}
      >
        <div className="p-4 shrink-0" style={{ borderBottom: "1px solid rgba(255,255,255,0.07)" }}>
          <div className="flex items-center justify-between mb-3">
            <h1 className="font-bold" style={{ color: "rgba(255,255,255,0.92)" }}>Reports</h1>
            <button
              onClick={() => { setShowBuilder(true); setSelected(null); }}
              className="p-1.5 rounded-lg transition-all"
              style={{ background: "rgba(201,162,39,0.15)", color: "#C9A227", border: "1px solid rgba(201,162,39,0.3)" }}
            >
              <Plus className="w-4 h-4" />
            </button>
          </div>
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5" style={{ color: "rgba(255,255,255,0.3)" }} />
            <input
              value={search} onChange={e => setSearch(e.target.value)}
              placeholder="Search reports..."
              className="w-full pl-8 pr-3 py-2 rounded-lg text-xs outline-none text-white"
              style={{ background: "rgba(255,255,255,0.055)", border: "1px solid rgba(255,255,255,0.09)" }}
            />
          </div>
        </div>
        <div className="flex-1 overflow-y-auto scrollbar-hide">
          {filtered.map(r => (
            <ReportRow key={r.id} report={r} selected={selected?.id === r.id && !showBuilder} onClick={() => { setSelected(r); setShowBuilder(false); }} />
          ))}
        </div>
      </div>

      {/* ── Right: Detail / Builder ───────────────────────────── */}
      <div className={`flex-1 overflow-y-auto scrollbar-hide ${hasActiveSelection ? "flex" : "hidden md:flex"} flex-col`}>
        <AnimatePresence mode="wait">

          {/* Report Builder */}
          {showBuilder && (
            <motion.div key="builder" initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0 }} className="p-4 md:p-5 flex flex-col gap-5 h-full">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <button 
                    onClick={() => setShowBuilder(false)} 
                    className="md:hidden px-3 py-1.5 rounded-xl text-xs font-bold"
                    style={{ background: "rgba(255,255,255,0.06)", color: "rgba(255,255,255,0.6)", border: "1px solid rgba(255,255,255,0.1)" }}
                  >
                    ← Back
                  </button>
                  <h2 className="text-lg font-bold" style={{ color: "rgba(255,255,255,0.92)" }}>AI Draft Generator</h2>
                </div>
                <button onClick={() => setShowBuilder(false)} className="text-xs hidden md:block" style={{ color: "rgba(255,255,255,0.4)" }}>Cancel</button>
              </div>

              <GlassCard>
                <div className="flex flex-col gap-4">
                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] font-bold uppercase tracking-widest" style={{ color: "rgba(255,255,255,0.4)" }}>Case ID</label>
                    <input value={genCaseId} onChange={e => setGenCaseId(e.target.value)} placeholder="e.g. INC-007"
                      className="px-3 py-2 rounded-lg text-sm outline-none text-white"
                      style={{ background: "rgba(255,255,255,0.055)", border: "1px solid rgba(255,255,255,0.09)" }} />
                  </div>
                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] font-bold uppercase tracking-widest" style={{ color: "rgba(255,255,255,0.4)" }}>Report Type</label>
                    <select value={genType} onChange={e => setGenType(e.target.value)} className="px-3 py-2 rounded-lg text-sm outline-none text-white"
                      style={{ background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.09)" }}>
                      {["Incident Summary", "Chargesheet Draft", "FIR Draft", "Analytics Export"].map(t => (
                        <option key={t} value={t}>{t}</option>
                      ))}
                    </select>
                  </div>
                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] font-bold uppercase tracking-widest" style={{ color: "rgba(255,255,255,0.4)" }}>Key Facts / Notes</label>
                    <textarea value={genNotes} onChange={e => setGenNotes(e.target.value)} rows={3} placeholder="Add key facts, clauses, or special instructions..."
                      className="px-3 py-2 rounded-lg text-sm outline-none text-white resize-none"
                      style={{ background: "rgba(255,255,255,0.055)", border: "1px solid rgba(255,255,255,0.09)" }} />
                  </div>
                  <button onClick={handleGenerate} disabled={genState === "thinking" || genState === "streaming"}
                    className="py-3 rounded-xl font-bold text-sm text-black flex items-center justify-center gap-2"
                    style={{ background: "linear-gradient(135deg, #C9A227 0%, #e8b92e 100%)", opacity: genState !== "idle" && genState !== "done" ? 0.7 : 1 }}>
                    {genState === "thinking" || genState === "streaming" ? (
                      <><LiquidOrb size={20} isThinking={true} />Generating…</>
                    ) : "Generate Draft"}
                  </button>
                </div>
              </GlassCard>

              {/* Generated preview */}
              <AnimatePresence>
                {(genState === "streaming" || genState === "done") && (
                  <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}>
                    <GlassCard title="Generated Draft" action={
                      genState === "done" && (
                        <button className="text-xs font-bold px-3 py-1.5 rounded-lg flex items-center gap-1.5"
                          style={{ background: "rgba(46,158,108,0.15)", color: "#2E9E6C", border: "1px solid rgba(46,158,108,0.3)" }}>
                          <CheckCircle2 className="w-3.5 h-3.5" /> Accept Draft
                        </button>
                      )
                    }>
                      {genState === "streaming"
                        ? <StreamingText text={DRAFT_TEXT} onDone={() => setGenState("done")} />
                        : <pre className="text-xs leading-relaxed whitespace-pre-wrap font-mono" style={{ color: "rgba(255,255,255,0.75)" }}>{DRAFT_TEXT}</pre>
                      }
                    </GlassCard>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          )}

          {/* Report Detail */}
          {selected && !showBuilder && (
            <motion.div key={selected.id} initial={{ opacity: 0, x: 8 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0 }} className="p-4 md:p-5 flex flex-col gap-5">
              {/* Header */}
              <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-2">
                    <button 
                      onClick={() => setSelected(null)} 
                      className="md:hidden px-3 py-1.5 rounded-xl text-xs font-bold mr-1"
                      style={{ background: "rgba(255,255,255,0.06)", color: "rgba(255,255,255,0.6)", border: "1px solid rgba(255,255,255,0.1)" }}
                    >
                      ← Back
                    </button>
                    <ReportStatusBadge status={selected.status} />
                    <span className="text-[11px]" style={{ color: "rgba(255,255,255,0.3)" }}>{selected.type}</span>
                  </div>
                  <h2 className="text-xl font-bold" style={{ color: "rgba(255,255,255,0.92)" }}>{selected.title}</h2>
                  <div className="flex items-center gap-3 mt-1.5 text-xs flex-wrap" style={{ color: "rgba(255,255,255,0.35)" }}>
                    <span>Case: {selected.caseId}</span>
                    <span>·</span>
                    <span><Edit3 className="w-3 h-3 inline mr-0.5" />{selected.lastEditedBy}</span>
                    <span>·</span>
                    <span><Clock className="w-3 h-3 inline mr-0.5" />{new Date(selected.updatedAt).toLocaleDateString("en-IN")}</span>
                  </div>
                </div>
                <div className="flex gap-2 shrink-0 self-end sm:self-auto">
                  <button onClick={() => setShowHistory(p => !p)} className="p-2.5 rounded-xl" style={{ background: "rgba(255,255,255,0.06)", color: "rgba(255,255,255,0.5)", border: "1px solid rgba(255,255,255,0.09)" }}>
                    <History className="w-4 h-4" />
                  </button>
                  <button onClick={handleDownload} className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl text-sm font-bold"
                    style={{ background: "linear-gradient(135deg, #C9A227 0%, #e8b92e 100%)", color: "#000" }}>
                    <Download className="w-4 h-4" /> Export
                  </button>
                </div>
              </div>

              {/* Version History */}
              <AnimatePresence>
                {showHistory && (
                  <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }}>
                    <GlassCard title="Version History">
                      <div className="flex flex-col gap-3">
                        {selected.versionHistory.map(v => (
                          <div key={v.version} className="flex items-center gap-3">
                            <div className="w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold shrink-0"
                              style={{ background: "rgba(201,162,39,0.18)", color: "#C9A227" }}>v{v.version}</div>
                            <div>
                              <p className="text-sm" style={{ color: "rgba(255,255,255,0.75)" }}>{v.note}</p>
                              <p className="text-xs" style={{ color: "rgba(255,255,255,0.3)" }}>{v.editedBy} · {new Date(v.editedAt).toLocaleString("en-IN")}</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    </GlassCard>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Sections */}
              {selected.sections.map((sec, i) => (
                <GlassCard key={i} title={sec.heading}>
                  <p className="text-sm leading-relaxed" style={{ color: "rgba(255,255,255,0.72)" }}>{sec.content}</p>
                </GlassCard>
              ))}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
